---
title: "Mini-Project 2"
<<<<<<< HEAD
author: "Marcela Osorio, Teniel Rhiney, Nicole Lawler"
=======
author: "Marcela Osorio and Teniel Rhiney"
>>>>>>> 684a07bfd85a1393cdb831c22a97f54258bb1310
date: "2019-03-24"
output: 
  html_document:
    code_folding: hide
---


## Loading the data

<<<<<<< HEAD
This project is so interesting and relevant to my life,not really!



```{r, warning = FALSE, message=FALSE}

library(tidyverse)
library(ggplot2)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

> Word count: `r wordcountaddin::word_count()`


For more information please visit  ^[“sds192-mp2 repository” _GitHub_. https://github.com/beanumber/sds192-mp2. Accessed 8 March. 2019]


**Important:** We need to write annotations  

We are creating a new dataset with the variable that we are going to explore. 


```{r}
candidates <- as_tibble(candidates) 
candidates
```

```{r}
cc <- candidates %>%
  select("cand_id", "cand_name", "cand_state", "cand_party_affiliation", "cand_election_yr") %>%
  filter(cand_state == "MA")
cc
```

```{r}
graph_one <- ggplot(data = cc, aes(x = cand_party_affiliation)) +
  geom_bar()
graph_one
```




```{r}
contributions <- as_tibble(contributions) 
contributions
```

```{r}
cb <- contributions %>%
  select("cand_id", "transaction_type", "transaction_amt", "name", "entity_type", "state") %>%
  filter(state == "MA")
cb

```

```{r}

```



